// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: traces.sql

package db

import (
	"context"
)

const createTrace = `-- name: CreateTrace :one
INSERT INTO traces (id, session_id, started_at, stopped_at, event_count, data_jsonl, created_at)
VALUES (?, ?, ?, ?, ?, ?, strftime('%s', 'now'))
RETURNING id, session_id, started_at, stopped_at, event_count, data_jsonl, created_at
`

type CreateTraceParams struct {
	ID         string `json:"id"`
	SessionID  string `json:"session_id"`
	StartedAt  int64  `json:"started_at"`
	StoppedAt  int64  `json:"stopped_at"`
	EventCount int64  `json:"event_count"`
	DataJsonl  string `json:"data_jsonl"`
}

func (q *Queries) CreateTrace(ctx context.Context, arg CreateTraceParams) (Trace, error) {
	row := q.queryRow(ctx, q.createTraceStmt, createTrace,
		arg.ID,
		arg.SessionID,
		arg.StartedAt,
		arg.StoppedAt,
		arg.EventCount,
		arg.DataJsonl,
	)
	var i Trace
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.StartedAt,
		&i.StoppedAt,
		&i.EventCount,
		&i.DataJsonl,
		&i.CreatedAt,
	)
	return i, err
}

const getTraceByID = `-- name: GetTraceByID :one
SELECT id, session_id, started_at, stopped_at, event_count, data_jsonl, created_at FROM traces WHERE id = ? LIMIT 1
`

func (q *Queries) GetTraceByID(ctx context.Context, id string) (Trace, error) {
	row := q.queryRow(ctx, q.getTraceByIDStmt, getTraceByID, id)
	var i Trace
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.StartedAt,
		&i.StoppedAt,
		&i.EventCount,
		&i.DataJsonl,
		&i.CreatedAt,
	)
	return i, err
}

const listTracesBySession = `-- name: ListTracesBySession :many
SELECT id, session_id, started_at, stopped_at, event_count, data_jsonl, created_at FROM traces WHERE session_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListTracesBySession(ctx context.Context, sessionID string) ([]Trace, error) {
	rows, err := q.query(ctx, q.listTracesBySessionStmt, listTracesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Trace{}
	for rows.Next() {
		var i Trace
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.StartedAt,
			&i.StoppedAt,
			&i.EventCount,
			&i.DataJsonl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
